from pathlib import Path
import re, json

APP_VERSION='14.0.0'
files=['index.html','VialTrack.html']

icons={
'home':'<svg class="appNavSvg" viewBox="0 0 24 24" aria-hidden="true"><path d="M3.5 10.5 12 3.8l8.5 6.7v9.1a1.4 1.4 0 0 1-1.4 1.4h-5.2v-6.3h-3.8V21H4.9a1.4 1.4 0 0 1-1.4-1.4Z"/><path d="M8.8 21v-6.3h6.4V21"/></svg>',
'track':'<svg class="appNavSvg" viewBox="0 0 24 24" aria-hidden="true"><path d="M4 18.5h16"/><path d="m5.5 15 4-4 3 2.7 6-7"/><circle cx="5.5" cy="15" r="1"/><circle cx="9.5" cy="11" r="1"/><circle cx="12.5" cy="13.7" r="1"/><circle cx="18.5" cy="6.7" r="1"/></svg>',
'vials':'<svg class="appNavSvg" viewBox="0 0 24 24" aria-hidden="true"><path d="M8 3.5h8M9 6h6v2.2l1.9 2.1a3.6 3.6 0 0 1 .9 2.4v6.1a2.2 2.2 0 0 1-2.2 2.2H8.4a2.2 2.2 0 0 1-2.2-2.2v-6.1a3.6 3.6 0 0 1 .9-2.4L9 8.2Z"/><path d="M6.3 15.2h11.4"/></svg>',
'weight':'<svg class="appNavSvg" viewBox="0 0 24 24" aria-hidden="true"><rect x="4" y="5" width="16" height="15" rx="3"/><path d="M8 10a4 4 0 0 1 8 0"/><path d="m12 10 2-2"/><circle cx="12" cy="10" r=".8"/></svg>',
'more':'<svg class="appNavSvg" viewBox="0 0 24 24" aria-hidden="true"><circle cx="6" cy="12" r="1.4"/><circle cx="12" cy="12" r="1.4"/><circle cx="18" cy="12" r="1.4"/></svg>',
'history':'<svg class="appNavSvg" viewBox="0 0 24 24" aria-hidden="true"><path d="M5 6h14M5 12h14M5 18h14"/><circle cx="3" cy="6" r=".7"/><circle cx="3" cy="12" r=".7"/><circle cx="3" cy="18" r=".7"/></svg>',
'backup':'<svg class="appNavSvg" viewBox="0 0 24 24" aria-hidden="true"><path d="M12 3v12"/><path d="m8 11 4 4 4-4"/><path d="M5 19h14"/></svg>',
'nasal':'<svg class="appNavSvg" viewBox="0 0 24 24" aria-hidden="true"><path d="M10 3c2 2.5 3 5 3 7.5 0 3-1.2 5.2-3.6 6.6"/><path d="M13 8c3 .5 5 2.3 6 5"/><path d="M15.5 14.5h3"/></svg>',
}

more_panel=f'''\n  <section id="morePanel" class="morePanel appView hidden">\n    <div class="simpleScreenHeader"><div class="screenEyebrow">Vial</div><h2>More</h2></div>\n    <div class="moreGroup"><div class="moreGroupTitle">Tools</div>\n      <button class="moreRow" type="button" onclick="showView('nasal')"><span class="moreRowIcon">{icons['nasal']}</span><span><strong>Intranasal Calculator</strong><small>Nasal spray calculations</small></span><span class="moreChevron">›</span></button>\n    </div>\n    <div class="moreGroup"><div class="moreGroupTitle">Data & Backup</div>\n      <button class="moreRow" type="button" onclick="exportHistory()"><span class="moreRowIcon">{icons['backup']}</span><span><strong>Export Backup</strong><small>Save a copy of all Vial data</small></span><span class="moreChevron">›</span></button>\n      <label class="moreRow importMoreRow"><span class="moreRowIcon">{icons['history']}</span><span><strong>Import Backup</strong><small>Restore a Vial JSON backup</small></span><span class="moreChevron">›</span><input type="file" accept="application/json,.json" onchange="importHistoryFile(event)"></label>\n      <button class="moreRow dangerRow" type="button" onclick="eraseAllLocalData()"><span class="moreRowIcon eraseIcon">×</span><span><strong>Erase All Local Data</strong><small>Remove this device's Vial data</small></span><span class="moreChevron">›</span></button>\n    </div>\n    <div class="moreGroup"><div class="moreGroupTitle">About</div>\n      <div class="moreStaticRow"><span><strong>Vial</strong><small>Version {APP_VERSION}</small></span></div>\n      <div class="moreStaticRow"><span><strong>Data</strong><small>Stored on this device unless you export it</small></span></div>\n    </div>\n  </section>\n'''

home='''\n  <section id="homePanel" class="homePanel appView">\n    <div class="simpleHomeHead"><div><div id="homeTodayDate" class="todayDate"></div><h2>Today</h2></div><img src="./icon-192.png" class="simpleHomeIcon" alt="Vial"></div>\n    <div class="homePrimaryActions"><button class="homePrimaryBtn" type="button" onclick="homeQuickLog()">Log</button><button class="homePrimaryBtn secondary" type="button" onclick="showView('calculator')">Reconstitute</button></div>\n    <div class="homeCompactStats">\n      <button onclick="showView('tracker')"><span>Today</span><strong id="homeTodayEntryCount">0</strong></button>\n      <button onclick="showView('inventory')"><span>Active</span><strong id="homeActiveVialCount">0</strong></button>\n      <button onclick="showView('inventory')"><span>Stock</span><strong id="homeStockVialCount">0</strong></button>\n      <button onclick="showView('weight')"><span>Weight</span><strong id="homeWeightValue">—</strong></button>\n      <span id="homeWeekEntryCount" class="hidden">0</span><span id="homeHistoryCount" class="hidden">0</span>\n    </div>\n    <div class="homeSection homeSectionTight"><div class="homeSectionHeader"><div><div class="dashLabel">Today</div><h3>Log</h3></div><button class="homeTextBtn" onclick="openTrackerToday()">View</button></div><div id="homeTodayEntries" class="homeList"></div></div>\n    <div class="homeSection homeSectionTight"><div class="homeSectionHeader"><div><div class="dashLabel">Active</div><h3>Vials</h3></div><button class="homeTextBtn" onclick="showView('inventory')">View</button></div><div id="homeVialCards" class="homeVialGrid"></div></div>\n    <div id="homeRecentHistory" class="hidden"></div>\n  </section>'''

nav=f'''  <nav class="bottomNav" aria-label="Primary">\n    <button id="navHome" class="navBtn active" onclick="showView('home')"><span class="navIcon">{icons['home']}</span><span class="navLabel">Home</span></button>\n    <button id="navTracker" class="navBtn" onclick="showView('tracker')"><span class="navIcon">{icons['track']}</span><span class="navLabel">Track</span></button>\n    <button id="navInventory" class="navBtn" onclick="showView('inventory')"><span class="navIcon">{icons['vials']}</span><span class="navLabel">Vials</span></button>\n    <button id="navWeight" class="navBtn" onclick="showView('weight')"><span class="navIcon">{icons['weight']}</span><span class="navLabel">Weight</span></button>\n    <button id="navMore" class="navBtn" onclick="showView('more')"><span class="navIcon">{icons['more']}</span><span class="navLabel">More</span></button>\n  </nav>'''

css='''\n/* V14 simplified product structure */\n.bottomNav{grid-template-columns:repeat(5,1fr)!important}.simpleHomeHead{display:flex;justify-content:space-between;align-items:center;padding:8px 2px 12px}.simpleHomeHead h2{font-size:2rem;margin:3px 0 0}.simpleHomeIcon{width:48px;height:48px;border-radius:14px}.homePrimaryActions{display:grid;grid-template-columns:1fr 1fr;gap:9px;margin-bottom:10px}.homePrimaryBtn{min-height:52px;border:0;border-radius:14px;background:#19c7a2;color:#081511;font-size:.96rem;font-weight:800}.homePrimaryBtn.secondary{background:#26282c;color:#f5f5f6;border:1px solid var(--line2)}.homeCompactStats{display:grid;grid-template-columns:repeat(4,1fr);gap:7px;margin-bottom:10px}.homeCompactStats button{min-height:64px;padding:9px;border-radius:13px;background:#1d1f22;border:1px solid var(--line);color:var(--text);text-align:left}.homeCompactStats span{display:block;font-size:.62rem;text-transform:uppercase;letter-spacing:.07em;color:var(--muted2);font-weight:800}.homeCompactStats strong{display:block;font-size:1.2rem;margin-top:3px}.homeSectionTight{margin-top:9px!important}.simplifiedVialActions{display:grid!important;grid-template-columns:1fr 1fr;gap:7px!important}.subtleAction{opacity:.72}.simpleScreenHeader{padding:5px 2px 12px}.simpleScreenHeader h2{font-size:1.7rem;margin:2px 0}.morePanel{max-width:760px;margin:0 auto}.moreGroup{margin-bottom:14px;border-radius:18px;background:#1d1f22;border:1px solid var(--line);overflow:hidden}.moreGroupTitle{padding:13px 14px 7px;color:var(--muted2);font-size:.66rem;font-weight:800;text-transform:uppercase;letter-spacing:.08em}.moreRow,.moreStaticRow{width:100%;min-height:64px;display:grid;grid-template-columns:34px 1fr 18px;align-items:center;gap:10px;padding:10px 14px;border:0;border-top:1px solid rgba(255,255,255,.035);background:transparent;color:var(--text);text-align:left}.moreStaticRow{grid-template-columns:1fr}.moreRowIcon{width:30px;height:30px;display:grid;place-items:center;color:#19c7a2}.moreRowIcon .appNavSvg{width:21px;height:21px}.eraseIcon{font-size:1.4rem}.moreRow strong,.moreStaticRow strong{display:block;font-size:.9rem}.moreRow small,.moreStaticRow small{display:block;color:var(--muted);font-size:.72rem;margin-top:2px}.moreChevron{color:var(--muted2);font-size:1.3rem}.importMoreRow{cursor:pointer}.importMoreRow input{display:none}.dangerRow .moreRowIcon,.dangerRow strong{color:#dc8b8b}.header .offline-badge,.header .subtitle,.header h1{display:none!important}@media(max-width:640px){.bottomNav{grid-template-columns:repeat(5,1fr)!important}.navLabel{font-size:.63rem!important}.homeCompactStats button{min-height:58px;padding:7px}.homeCompactStats strong{font-size:1.05rem}}\n'''

erase='''<script>\nasync function eraseAllLocalData(){\n  if(!confirm('Erase all Vial data stored on this device? Export a backup first if you may want it later.')) return;\n  if(!confirm('This permanently removes local vials, logs, history, and weights from this device. Continue?')) return;\n  try{ if(vtDbPromise){ try{(await vtDbPromise).close()}catch(e){} } await new Promise((resolve,reject)=>{const r=indexedDB.deleteDatabase(VT_DB_NAME);r.onsuccess=resolve;r.onerror=()=>reject(r.error);r.onblocked=resolve;}); Object.keys(localStorage).filter(k=>k.toLowerCase().includes('vial')).forEach(k=>localStorage.removeItem(k)); location.reload(); }catch(e){alert('Could not erase local data. Close other Vial tabs and try again.')}\n}\n</script>'''

for fn in files:
    p=Path(fn)
    html=p.read_text(encoding='utf-8')
    html=re.sub(r'<meta name="vialtrack-version" content="[^"]+">',f'<meta name="vialtrack-version" content="{APP_VERSION}">',html,count=1)
    html=html.replace('VialTrack','Vial')
    html=re.sub(r"const VIAL_APP_VERSION = '[^']+';",f"const VIAL_APP_VERSION = '{APP_VERSION}';",html,count=1)
    html=re.sub(r"const VT_WEIGHT_SEED = \[.*?\n\];","const VT_WEIGHT_SEED = [];",html,count=1,flags=re.S)
    if "if(!VT_WEIGHT_SEED.length)" not in html:
        html=html.replace("    for(const r of VT_WEIGHT_SEED){","    if(!VT_WEIGHT_SEED.length){ localStorage.setItem(VT_WEIGHT_SEED_KEY,'done'); return; }\n    for(const r of VT_WEIGHT_SEED){",1)
    hs=html.find('<section id="homePanel"'); he=html.find('</section>',hs)+len('</section>')
    html=html[:hs]+home+html[he:]
    html=html.replace('Vial Inventory','Vials').replace('<h2>Inventory</h2>','<h2>Vials</h2>',1).replace('Track unopened stock and active reconstituted vials. Remaining active-vial quantity is calculated from linked tracker entries.','Stock and active vials.')
    html=re.sub(r'<div class="inventoryHeaderActions">.*?</div>','''<div class="inventoryHeaderActions simplifiedVialActions"><button class="heroBtn primary" type="button" onclick="showView('calculator')">Reconstitute</button><button class="heroBtn" type="button" onclick="openStockComposer()">Add Stock</button><button class="heroBtn" type="button" onclick="showView('history')">History</button><button class="heroBtn subtleAction" type="button" onclick="openAddActiveVial()">Add Active</button></div>''',html,count=1,flags=re.S)
    html=html.replace('Saved vial setups','Reconstitution History').replace('Saved locally on this device. Reuse a prior setup to load it back into the calculator.','Saved vial setups.').replace('<div class="emptyIcon">VT</div>','<div class="emptyIcon">V</div>')
    html=re.sub(r'\n      <div class="historyActions">.*?</div>', '', html, count=1, flags=re.S)
    html=html.replace('  <div id="appUpdateOverlay"',more_panel+'\n  <div id="appUpdateOverlay"',1)
    html=re.sub(r'  <nav class="bottomNav" aria-label="Primary">.*?</nav>',nav,html,count=1,flags=re.S)
    html=html.replace("  const history = q('historyPanel');\n  const nasal = q('panelNasal');","  const history = q('historyPanel');\n  const more = q('morePanel');\n  const nasal = q('panelNasal');",1)
    html=html.replace("  if(history) history.classList.toggle('hidden', view !== 'history');\n  if(nasal) nasal.classList.toggle('hidden', view !== 'nasal');","  if(history) history.classList.toggle('hidden', view !== 'history');\n  if(more) more.classList.toggle('hidden', view !== 'more');\n  if(nasal) nasal.classList.toggle('hidden', view !== 'nasal');",1)
    html=re.sub(r"const navMap = \{.*?\};\n  \[.*?\]\.forEach", "const navMap = {home:'navHome', tracker:'navTracker', inventory:'navInventory', weight:'navWeight', more:'navMore', calculator:'navInventory', history:'navInventory', nasal:'navMore'};\n  ['navHome','navTracker','navInventory','navWeight','navMore'].forEach",html,count=1,flags=re.S)
    html=html.replace("  }else if(view === 'weight'){\n    prepareWeightTracker();\n  }else if(view === 'home'){","  }else if(view === 'weight'){\n    prepareWeightTracker();\n  }else if(view === 'more'){\n    // Static screen.\n  }else if(view === 'home'){",1)
    html=html.replace("['home','calculator','tracker','inventory','weight','history','nasal'].includes(state.currentView)","['home','calculator','tracker','inventory','weight','history','more','nasal'].includes(state.currentView)")
    html=html.replace('</style>',css+'\n</style>',1).replace('</body>',erase+'\n</body>',1)
    p.write_text(html,encoding='utf-8')

manifest=Path('manifest.json'); data=json.loads(manifest.read_text()); data.update({'name':'Vial','short_name':'Vial','description':'Vial: local vial inventory, tracking, reconstitution, and weight.','background_color':'#101113','theme_color':'#101113'}); manifest.write_text(json.dumps(data,indent=2)+'\n')
version=Path('version.json'); data=json.loads(version.read_text()); data.update({'app':'Vial','version':APP_VERSION,'build':14,'update_behavior':'prompt'}); version.write_text(json.dumps(data,indent=2)+'\n')
sw=Path('sw.js'); text=sw.read_text(); text=re.sub(r"const CACHE_NAME = '.*?';","const CACHE_NAME = 'vial-v14-1';",text); text=re.sub(r"const APP_VERSION = '.*?';",f"const APP_VERSION = '{APP_VERSION}';",text); sw.write_text(text)
Path('README.txt').write_text('Vial v14\n\nPublic build. Contains no personal seed data.\n\nNavigation: Home, Track, Vials, Weight, More.\nVials contains stock, active vials, reconstitution, and reconstitution history.\nMore contains intranasal calculator, backup/restore, local-data reset, and version information.\n\nPersonal data stays local unless explicitly exported.\n')
